### ISSUE TITLE
They required a higher minimum deployment target

### ISSUE THREAD

**Issue by deepak-sankey** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#23]
Got this error -> Specs satisfying the `MSPeekCollectionViewDelegateImplementation` dependency were found, but they required a higher minimum deployment target

**Comment by MaherKSantina** [comment]
Thank you @deepak-sankey for sharing this issue. I'm sorry I haven't checked it earlier I didn't see the notification on Github. I'll check it out for you 👍

**Comment by MaherKSantina** [comment]
@deepak-sankey the issue should be fixed. Please feel free to open this issue again if the problem persists 👍
