### ISSUE TITLE
How to get back to the first item when I am on the last one?

### ISSUE THREAD

**Issue by JhonnyTawk** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#28]

**Comment by MaherKSantina** [comment]
Thanks for raising this issue @JhonnyTawk. Currently there's no built in function that scrolls programmatically to a specific index. However, you can still achieve this easily.
You can use the function `setContentOffset` on the collection view as such:
```swift
collectionView.setContentOffset(CGPoint(x: 0, y: 0), animated: true)
```
Or alternatively, if you want to scroll to a specific item that is not the first one, you can use the function `scrollView(_:contentOffsetForItemAtIndex:)` and then create a `CGPoint` depending on whether the peeking is vertical or horizontal. And then you can use the `setContentOffset` passing the point you created.
Please note that when you scroll with your finger, you get a callback `peekImplementation(_:didChangeActiveIndexTo:)` which provides you with the current destination index for the item. But if you programmatically set the content offset using the functions mentioned, you won't get this callback. If this is a problem please let me know and I can make an update for the library which includes the change you need.

**Comment by JhonnyTawk** [comment]
Thanks @MaherKSantina 
I still have one question about `MSPeekImplementationDelegate` the implementation is correct I already double checked everything I am not able to access 
`func peekImplementation(_ peekImplementation: MSPeekCollectionViewDelegateImplementation, didChangeActiveIndexTo activeIndex: Int)`
on scroll.

 ```
peekImplementation = MSPeekCollectionViewDelegateImplementation()
        collectionView.configureForPeekingDelegate()
        peekImplementation.delegate = self
        peekImplementation = MSPeekCollectionViewDelegateImplementation(cellSpacing: 0, cellPeekWidth: 0, scrollThreshold: 1, maximumItemsToScroll: 5, numberOfItemsToShow: 1)
        collectionView.delegate = peekImplementation
        collectionView.dataSource = self
```
