### ISSUE TITLE
MSPeekImplementationDelegate returning nil

### ISSUE THREAD

**Issue by JhonnyTawk** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#29]
I want to get the active index i implemented MSPeekImplementationDelegate the implementation is correct I already double checked everything The 
`func peekImplementation(_ peekImplementation: MSPeekCollectionViewDelegateImplementation, didChangeActiveIndexTo activeIndex: Int)` is not being called.
This is my implemetation:

```
peekImplementation = MSPeekCollectionViewDelegateImplementation()
       collectionView.configureForPeekingDelegate()
       peekImplementation.delegate = self
       peekImplementation = MSPeekCollectionViewDelegateImplementation(cellSpacing: 0, cellPeekWidth: 0, scrollThreshold: 1, maximumItemsToScroll: 5, numberOfItemsToShow: 1)
       collectionView.delegate = peekImplementation
       collectionView.dataSource = self
```

**Comment by MaherKSantina** [comment]
Hello @JhonnyTawk, thank you for raising this issue. In the code snippet you provided you're initializing the `peekImplementation` variable twice (On the first line and on the 4th line). So after you're initializing it the second time you're not setting the delegate so that's why it's nil

**Comment by JhonnyTawk** [comment]
even like this didn't work : 
```
peekImplementation = MSPeekCollectionViewDelegateImplementation()
        collectionView.configureForPeekingDelegate()
        peekImplementation.delegate = self
        peekImplementation = MSPeekCollectionViewDelegateImplementation(cellSpacing: 0, cellPeekWidth: 0, scrollThreshold: 1, maximumItemsToScroll: imagesArray.count, numberOfItemsToShow: 1)
        collectionView.dataSource = self
```

**Comment by JhonnyTawk** [comment]
Thank you 👍
