### ISSUE TITLE
Listen for index change is not working

### ISSUE THREAD

**Issue by iloo123** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#32]
Listen for index change. Ive done exactly as on the docs. But current index Index change part doesn't work

**Comment by MaherKSantina** [comment]
Hello @iloo123, I'm sorry you're experiencing this problem. Please provide me with code snippets of what you did so I can investigate the issue with you.
Also, have you tried to clone the example and run it? The view controller in the example implements `func peekImplementation(_ peekImplementation: MSPeekCollectionViewDelegateImplementation, didChangeActiveIndexTo activeIndex: Int)` and prints the active index on each change.

**Comment by MaherKSantina** [comment]
Hello @iloo123, this issue has been open for over a month but I haven't heard back from you yet 😢 I'm afraid I'd have to close this issue for now. Please feel free to open it again if you're still experiencing the issue
Cheers
