### ISSUE TITLE
iOS 9.3 support

### ISSUE THREAD

**Issue by NEXTKING** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#40]
Hello, thanks for this nice implementation, but why did you drop support of iOS 9.3 starting from v. 1.2.0? It works perfectly on iOS 9 and no need for additional legacy code.

**Comment by MaherKSantina** [comment]
Hello @NEXTKING ! Thanks for raising the issue! I didn't know that some developers are still on iOS 9.3 as its market share is very low (2.9%). But you're right it's working anyways on that version so I shouldn't drop it. I'll make a release to restore that support! Sorry for the inconvenience!

**Comment by NEXTKING** [comment]
I agree that the share is non-significant and personally I would drop it myself, but there are still a lot of people using iPod 5th generation (I bet especially for enterprise apps) which can't be upgraded more than 9.3. Thank you!

**Comment by MaherKSantina** [comment]
@NEXTKING version 1.2.1 is live and supports iOS 9! 🎉 Thanks for raising this issue. Feel free to close it when you test the new version and confirm it's working! 👍

**Comment by MaherKSantina** [comment]
> I agree that the share is non-significant and personally I would drop it myself, but there are still a lot of people using iPod 5th generation (I bet especially for enterprise apps) which can't be upgraded more than 9.3. Thank you!

Ohh that's a good note I'll keep that in mind!

**Comment by NEXTKING** [comment]
Everything's fine now, thank you again!

**Comment by MaherKSantina** [comment]
No worries mate 👍 Thank you for your feedback!
