### ISSUE TITLE
Upgade to swift 4 (Xcode 10.2)

### ISSUE THREAD

**Issue by Bernix01** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#41]
As Xcode 10.2, Swift 3.x is no longer supported for building or migrating.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/5255494/55335939-b4990980-5461-11e9-838f-bbf89c981060.png">

**Comment by Bernix01** [comment]
My bad, was using outdated version, just had to update.

**Comment by MaherKSantina** [comment]
No worries @Bernix01! Let me know if you experience any issues :+1:
