### ISSUE TITLE
Scrolling does not work when collection view is on top of a scroll view

### ISSUE THREAD

**Issue by TheBigBiggerRice** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#47]
This repo helped me immensely! There is one issue I am not sure of is how to get the scrolling or delegate methods to work when my collection view is a subview of a scroll view. It seems like the collection view stopped working completely  when on a scroll view.

**Comment by MaherKSantina** [comment]
Hello @TheBigBiggerRice ! I'm really thrilled that this repo helped you out! I'm assuming that you were able to solve the issue by yourself? Let me know if you experience any more issues 👍
