### ISSUE TITLE
First item in the cell auto scrolling when i set the collection view leading or X by setting -60 to avoid cell peek width.

### ISSUE THREAD

**Issue by saikishoreagrapalem** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#51]
When i set the collection view x axis as -60 to avoid cell peek width and first item is auto scrolling after swiping the collection view. How to avoid this issue?

**Comment by MaherKSantina** [comment]
Hey @saikishoreagrapalem! Thanks for raising up this issue!
I just want to know how exactly are you setting the x-axis? Can you please show me a small piece of code where you're doing that?

Cheers

**Comment by MaherKSantina** [comment]
Hello @saikishoreagrapalem , I just wanted to let you know that I completely re-developed the library, if you want you can try with the new logic and see if it's working as expected. In the meantime I have to close this issue to avoid issues piling up. But feel free to open a new issue if you're facing other problems!
Cheers
