### ISSUE TITLE
Add SPM Support

### ISSUE THREAD

**Issue by GaneshMyNewCar** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#59]

**Comment by MaherKSantina** [comment]
Hello @GaneshMyNewCar ! So sorry for the 2 months late reply, I've been very busy at work and you know the whole COVID situation. I've just made an update to the library (3.1.0) to support SPM! Please check it out. 
I'll close this ticket for now. Feel free to re-open it if you find any issues

Have a great day and stay safe!

**Comment by GaneshMyNewCar** [comment]
Hi @MaherKSantina, Thanks for the Update. It's really appreciated and helpful.
Stay Home and Stay Safe.
