### ISSUE TITLE
extra space !?

### ISSUE THREAD

**Issue by ahmedsafadii** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#66]
behavior = MSCollectionViewPeekingBehavior(cellSpacing: 0)
        behavior = MSCollectionViewPeekingBehavior(cellPeekWidth: 0)
        behavior = MSCollectionViewPeekingBehavior(minimumItemsToScroll: 1)
        behavior = MSCollectionViewPeekingBehavior(maximumItemsToScroll: 1)
        behavior = MSCollectionViewPeekingBehavior(numberOfItemsToShow: 1)
        leagueCollectionView.configureForPeekingBehavior(behavior: behavior)

why this extra space !!?

![Simulator Screen Shot - iPhone SE - 2020-05-24 at 15 55 51](https://user-images.githubusercontent.com/6974081/82754658-11c6eb80-9dd7-11ea-80a6-e8a2592b79cb.png)

cell

<img width="371" alt="Screen Shot 2020-05-24 at 3 56 31 PM" src="https://user-images.githubusercontent.com/6974081/82754671-358a3180-9dd7-11ea-8b90-a6f8fee30fcd.png">

**Comment by ahmedsafadii** [comment]
behavior = MSCollectionViewPeekingBehavior(cellPeekWidth: 0)
        behavior = MSCollectionViewPeekingBehavior(minimumItemsToScroll: 1)
        behavior = MSCollectionViewPeekingBehavior(maximumItemsToScroll: 1)
        behavior = MSCollectionViewPeekingBehavior(numberOfItemsToShow: 1)
        print("Dsada", behavior.cellSpacing)
        print("Dsada", behavior.cellPeekWidth)
        leagueCollectionView.configureForPeekingBehavior(behavior: behavior)

it  looks like that it prints default value 20 and ignore the value that I set

**Comment by MaherKSantina** [comment]
Hello @ahmedsafadii , thank you for reaching out and contributing to this repository by opening this issue!
I think the README is not very clear concerning this. If you want to pass multiple parameters to the behavior (`cellPeekWidth`, `minimumItemsToScroll`, `maximumItemsToScroll` and `numberOfItemsToShow`), then you need to use 1 initializer call, not 4 different ones. So you should do this:
```swift
behavior = MSCollectionViewPeekingBehavior(cellPeekWidth: 0, minimumItemsToScroll: 1, maximumItemsToScroll: 1, numberOfItemsToShow: 1)
```
Instead of:
```swift
behavior = MSCollectionViewPeekingBehavior(cellPeekWidth: 0)
behavior = MSCollectionViewPeekingBehavior(minimumItemsToScroll: 1)
behavior = MSCollectionViewPeekingBehavior(maximumItemsToScroll: 1)
behavior = MSCollectionViewPeekingBehavior(numberOfItemsToShow: 1)
```

Please let me know if this helps

**Comment by ahmedsafadii** [comment]
Yes it works 👍

**Comment by MaherKSantina** [comment]
Awesome! Have a great day 👍
