### ISSUE TITLE
Top and Bottom spacing of UICollectionViewCell cut 

### ISSUE THREAD

**Issue by Thonyvb** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#68]
First, thanks for your framework it has helped a lot! 

I have an issue: My custom UICollectionViewCell has a shadow at the bottom, but MSPeekCollectionViewDelegateImplementation is cutting the shadow. Is there a way to add extra spacing to top and bottom between the UICollectionViewCell and collectionView height so the shadow appears?

Thanks!

**Comment by MaherKSantina** [comment]
Hello @Thonyvb! Thank you so much and thank you for opening this issue!
Okay so for this we have 2 solutions without changing the library:
1. Disable `Clips to Bounds` on the `UICollectionViewCell` and the parent views of the one with the shadow
2. Make the shadow span on a subview of the `UICollectionViewCell` not the `UICollectionViewCell` itself, and add some margins around the subview depending on how big the shadow is

Please let me know if what I wrote doesn't make sense I'm happy with explaining them more

Have a great day!

**Comment by Thonyvb** [comment]
Thanks a lot! It works as expected now!
